-- Track peer interest in draft terms
create table if not exists public.term_requests (
  id bigint generated by default as identity primary key,
  term_id uuid not null references public.terms(id) on delete cascade,
  source text, -- 'viewer' or 'creator'
  post_slug text,
  created_at timestamptz not null default now()
);

create index if not exists term_requests_term_id_idx on public.term_requests(term_id);
create index if not exists term_requests_created_at_idx on public.term_requests(created_at);

-- Utility function to mark a term as published when interest threshold is met
-- For V1 we keep thresholds small; adjust later.
create or replace function public.bump_term_interest(p_term_id uuid)
returns void
language plpgsql
as $$
declare
  interest_count integer;
begin
  select count(*) into interest_count from public.term_requests where term_id = p_term_id;
  if interest_count >= 5 then
    update public.terms
      set status = 'published',
          updated_at = now()
      where id = p_term_id
      and status = 'draft';
  end if;
end;
$$;
